import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prato Rápido",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={inter.className}
    >
      <body className="min-h-screen font-sans antialiased bg-white">
        <link rel="icon" href="/images/logo_prato_rapido.png" sizes="any" />
        {children}
      </body>
    </html>
  );
}
